### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by MOMANI1** [Quinny898/PersistentSearch#106]
when i opened the search box and then I closed the app
`Shutting down VM
04-24 19:18:19.584 8600-8600/android.alcode.com.material E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: android.alcode.com.material, PID: 8600
                                                                           java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to android.app.Activity
                                                                               at com.quinny898.library.persistentsearch.SearchBox.dispatchKeyEvent(SearchBox.java:948)
                                                                               at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                               at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                               at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                               at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                               at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                               at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                               at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                               at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                               at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                               at com.android.internal.policy.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:2395)
                                                                               at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1727)
                                                                               at android.app.Activity.dispatchKeyEvent(Activity.java:2725)
                                                                               at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:524)
                                                                               at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:50)
                                                                               at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:241)
                                                                               at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:50)
                                                                               at com.android.internal.policy.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2310)
                                                                               at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4127)
                                                                               at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4089)
                                                                               at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                               at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                               at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                               at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
                                                                               at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                               at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
                                                                               at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                               at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                               at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                               at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                               at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                               at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                               at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                               at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3820)
                                                                               at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3981)
                                                                               at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2253)
                                                                               at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1874)
                                                                               at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1865)
                                                                               at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2230)
                                                                               at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
                                                                               at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                               at android.os.MessageQueue.next(MessageQueue.java:323)
                                                                               at android.os.Looper.loop(Looper.java:135)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by MOMANI1** [comment]
hello
