### ISSUE TITLE
java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. 

### ISSUE THREAD

**Issue by MarcusJacobsson** [Quinny898/PersistentSearch#14]
I've implemented the SearchBox as the example show, but I'm getting the following error when I search, then try to search a second time:

java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(2131296374, class android.widget.ListView) with Adapter(class com.quinny898.library.persistentsearch.SearchBox$SearchAdapter)]

As I said, the implementation is identical to the example provided in the readme file. If anyone could help me out here, I would really appreciate it, thanks. 

Full stacktrace:

03-27 17:42:16.877    2775-2775/testing.august.com.haxx E/InputEventReceiver﹕ Exception dispatching input event.
03-27 17:42:16.877    2775-2775/testing.august.com.haxx E/MessageQueue-JNI﹕ Exception in MessageQueue callback: handleReceiveCallback
03-27 17:42:16.877    2775-2775/testing.august.com.haxx E/MessageQueue-JNI﹕ java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(2131296374, class android.widget.ListView) with Adapter(class com.quinny898.library.persistentsearch.SearchBox$SearchAdapter)]
            at android.widget.ListView.layoutChildren(ListView.java:1555)
            at android.widget.AbsListView.onTouchModeChanged(AbsListView.java:3363)
            at android.view.ViewTreeObserver.dispatchOnTouchModeChanged(ViewTreeObserver.java:879)
            at android.view.ViewRootImpl.ensureTouchModeLocally(ViewRootImpl.java:3290)
            at android.view.ViewRootImpl.ensureTouchMode(ViewRootImpl.java:3274)
            at android.view.ViewRootImpl$EarlyPostImeInputStage.processPointerEvent(ViewRootImpl.java:3769)
            at android.view.ViewRootImpl$EarlyPostImeInputStage.onProcess(ViewRootImpl.java:3737)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3399)
            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5602)
            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5582)
            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5553)
            at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5682)
            at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
            at android.os.MessageQueue.nativePollOnce(Native Method)
            at android.os.MessageQueue.next(MessageQueue.java:138)
            at android.os.Looper.loop(Looper.java:123)
            at android.app.ActivityThread.main(ActivityThread.java:5017)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by LouisLeung** [comment]
I have same problem. I change the code
if (listener != null) {
                    listener.onSearchTermChanged(s.toString());
                } 
to
if (listener != null) {
                    listener.onSearchTermChanged(s.toString());
                    ((SearchAdapter) results.getAdapter()).notifyDataSetChanged(); <--
                }
from
SearchBox(Context context, AttributeSet attrs, int defStyle) {}

**Comment by Quinny898** [comment]
Again, I think this was fixed in the update, comment if not

**Comment by IlyaEremin** [comment]
This was not fixed...

**Comment by liericiyan** [comment]
This was not fixed...
