### ISSUE TITLE
dispatchKeyEvent of SearchBox throws a ClassCast Exception

### ISSUE THREAD

**Issue by eirinaios** [Quinny898/PersistentSearch#67]
Congrats for your work on this amazing library.

Here's a problem which has proven quite serious. Whenever the search box is shown (followed by a call to revealFromMenuItem()) and I press the back button, this event is intercepted by dispatchKeyEvent. For your reference, I paste the code of that function directly:
 
```
public boolean dispatchKeyEvent(KeyEvent e) {
        if(e.getKeyCode() == 4 && this.getVisibility() == 0) {
            this.hideCircularly((Activity)this.getContext());
            return true;
        } else {
            return super.dispatchKeyEvent(e);
        }
    }
```

The first check succeeds, but inside the call of hideCircularly, the type cast of this.getContext() to Activity fails and my app crashes. At least for me, the context is of type android.support.v7.internal.view.ContextThemeWrapper. The search box in my case resides inside the Toolbar. When it is revealed, it extends the toolbar and appears below the main bar. The exception thrown is:
```
java.lang.ClassCastException: android.support.v7.internal.view.ContextThemeWrapper cannot be cast to android.app.Activity
10-01 10:42:26.242 20514-20514/rapps.com.athonitetime E/AndroidRuntime:     at com.quinny898.library.persistentsearch.SearchBox.dispatchKeyEvent(SearchBox.java:948)
10-01 10:42:26.242 20514-20514/rapps.com.athonitetime E/AndroidRuntime:     at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1359)
10-01 10:42:26.242 20514-20514/rapps.com.athonitetime E/AndroidRuntime:     at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1359)
10-01 10:42:26.242 20514-20514/rapps.com.athonitetime E/AndroidRuntime:     at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1359)
10-01 10:42:26.242 20514-20514/rapps.com.athonitetime E/AndroidRuntime:     at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1359)
10-01 10:42:26.242 20514-20514/rapps.com.athonitetime E/AndroidRuntime:     at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1359)
10-01 10:42:26.242 20514-20514/rapps.com.athonitetime E/AndroidRuntime:     at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1359)
10-01 10:42:26.242 20514-20514/rapps.com.athonitetime E/AndroidRuntime:     at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1359)
10-01 10:42:26.242 20514-20514/rapps.com.athonitetime E/AndroidRuntime:     at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1359)
10-01 10:42:26.242 20514-20514/rapps.com.athonitetime E/AndroidRuntime:     at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1359)
10-01 10:42:26.242 20514-20514/rapps.com.athonitetime E/AndroidRuntime:     at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:1920)
10-01 10:42:26.242 20514-20514/rapps.com.athonitetime E/AndroidRuntime:     at com.android.internal.policy.impl.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1395)
10-01 10:42:26.242 20514-20514/rapps.com.athonitetime E/AndroidRuntime:     at android.app.Activity.dispatchKeyEvent(Activity.java:2370)
10-01 10:42:26.242 20514-20514/rapps.com.athonitetime E/AndroidRuntime:     at android.support.v7.internal.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:50)
10-01 10:42:26.242 20514-20514/rapps.com.athonitetime E/AndroidRuntime:     at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:224)
10-01 10:42:26.242 20514-20514/rapps.com.athonitetime E/AndroidRuntime:     at android.support.v7.internal.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:50)
10-01 10:42:26.242 20514-20514/rapps.com.athonitetime E/AndroidRuntime:     at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1847)
10-01 10:42:26.242 20514-20514/rapps.com.athonitetime E/AndroidRuntime:     at android.view.ViewRootImpl.deliverKeyEventPostIme(ViewRootImpl.java:3701)
10-01 10:42:26.242 20514-20514/rapps.com.athonitetime E/AndroidRuntime:     at android.view.ViewRootImpl.handleImeFinishedEvent(ViewRootImpl.java:3651)
10-01 10:42:26.242 20514-20514/rapps.com.athonitetime E/AndroidRuntime:     at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:2818)
10-01 10:42:26.242 20514-20514/rapps.com.athonitetime E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:99)
10-01 10:42:26.242 20514-20514/rapps.com.athonitetime E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:137)
10-01 10:42:26.242 20514-20514/rapps.com.athonitetime E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5041)
10-01 10:42:26.242 20514-20514/rapps.com.athonitetime E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
10-01 10:42:26.242 20514-20514/rapps.com.athonitetime E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511)
10-01 10:42:26.242 20514-20514/rapps.com.athonitetime E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
10-01 10:42:26.242 20514-20514/rapps.com.athonitetime E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
10-01 10:42:26.242 20514-20514/rapps.com.athonitetime E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)
```

Would it be possible to look into it and correct is as soon as possible please?
Thank you in advance

**Comment by Quinny898** [comment]
I'm not seeing this problem with the sample, are you using the same code as that?

**Comment by eirinaios** [comment]
The problem doesn't arise in the sample, because the context of the SearchBox happens to be the Activity. Since I'm placing the SearchBox inside AppBarLayout, getContext does not return the Activity! Here's my layout:
```
<android.support.design.widget.AppBarLayout
        android:id="@+id/appbar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:fitsSystemWindows="true"
        android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar">

        <android.support.v7.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_height="?attr/actionBarSize"
            android:layout_width="match_parent"
            app:popupTheme="@style/ThemeOverlay.AppCompat.Light"
            app:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar"
            app:layout_scrollFlags="scroll|enterAlways">
        </android.support.v7.widget.Toolbar>

        <com.astuetz.PagerSlidingTabStrip
            android:id="@+id/tabsStrip"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:background="?attr/colorPrimary"/>

        <com.quinny898.library.persistentsearch.SearchBox
            android:layout_width="wrap_content"
            android:id="@+id/searchbox"
            android:layout_height="wrap_content"
            android:visibility="gone"/>

    </android.support.design.widget.AppBarLayout>
```

I guess you could resolve the problem by using the mContainerActivity member variable.

**Comment by ubeyou** [comment]
any solution for this? I'm having the same problem.

**Comment by Quinny898** [comment]
Can one of you with the bug post the code you are using so I can test and fix the bug? Like I said, I don't have it so can't really do anything

**Comment by eirinaios** [comment]
Hi Quinny,

I've already posted my code (which is really my layout). The problem is that when I get the reference to the SearchBox object inside the ```onCreateView```, being inside an AppBarLayout, its context is not the Activity but something else (in particular ```ContextThemeWrapper```). I've corrected the error by replacing the call to ```this.getContext()``` inside ```dispatchKeyEvent``` with ```this.mContainerActivity```, which is bound to work, provided that the user followed your instructions and during initialization called ```search.enableVoiceRecognition(this);```

**Comment by jameltheone** [comment]
Facing the same problem (SearchBox is inside AppBarLayout)

**Comment by IlyaEremin** [comment]
Here is my solution. I use `SearchBox` inside `Fragment` and I call `setActivity(getActivity())` in `onViewCreated`
https://gist.github.com/IlyaEremin/366b1753c24ed2302ae6

**Comment by Sermilion** [comment]
It seems the problem has not been fixed yet. It happens you place searchbox to toolbar.
