### ISSUE TITLE
The content of the adapter has changed but ListView did not receive a notification

### ISSUE THREAD

**Issue by therajanmaurya** [Quinny898/PersistentSearch#73]
```
    10-15 13:06:34.928  17218-17218/com.sample.app E/InputEventReceiver﹕ Exception dispatching input event.
10-15 13:06:34.929  17218-17218/com.sapmle.app E/MessageQueue-JNI﹕ Exception in MessageQueue callback: handleReceiveCallback
10-15 13:06:34.929  17218-17218/com.sample.app E/MessageQueue-JNI﹕ java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(2131558546, class android.widget.ListView) with Adapter(class com.quinny898.library.persistentsearch.SearchBox$SearchAdapter)]
            at android.widget.ListView.layoutChildren(ListView.java:1572)
            at android.widget.AbsListView.onTouchModeChanged(AbsListView.java:3587)
            at android.view.ViewTreeObserver.dispatchOnTouchModeChanged(ViewTreeObserver.java:997)
            at android.view.ViewRootImpl.ensureTouchModeLocally(ViewRootImpl.java:3533)
            at android.view.ViewRootImpl.ensureTouchMode(ViewRootImpl.java:3517)
            at android.view.ViewRootImpl$EarlyPostImeInputStage.processPointerEvent(ViewRootImpl.java:4032)
            at android.view.ViewRootImpl$EarlyPostImeInputStage.onProcess(ViewRootImpl.java:4000)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5922)
            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5896)
            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5857)
            at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6025)
            at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
            at android.os.MessageQueue.nativePollOnce(Native Method)
            at android.os.MessageQueue.next(MessageQueue.java:323)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5417)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by IlyaEremin** [comment]
+1 I have no ListView yet, but I get this error. WTF?

**Comment by Vieuma** [comment]
+1 Also have this error.

**Comment by udayathreya** [comment]
add this ((ArrayAdapter)((ListView)search.findViewById(R.id.results)).getAdapter()).notifyDataSetChanged(); to all of the search methods before doing anything and you wont see the error

**Comment by RommelLiang** [comment]
+1 I also have this error
