### ISSUE TITLE
Error when press back button to dismiss

### ISSUE THREAD

**Issue by KiengKnot** [Quinny898/PersistentSearch#84]
The problem is occurred when i opened search then pressed back button to dismiss the search and then this error happened every time i press. 
i have tried many way to solve the error as below, but i still could not solved it until i comment code like this and it work, but the UI of search widget is still remain
```java
protected void closeSearch() {
        search.clearSearchable();
//        search.hideCircularly(this);
        if (search.getSearchText().isEmpty())
            toolbar.setTitle(getResources().getString(R.string.app_name));
    }  
```

when i follow an error reference it refers to this function of library (SearchBox.java line  675-682)
```java    
public boolean dispatchKeyEvent(KeyEvent e) {
        if(e.getKeyCode() == 4 && this.getVisibility() == 0) {
            this.hideCircularly((Activity)this.getContext());
            return true;
        } else {
            return super.dispatchKeyEvent(e);
        }
    }
```

here is the error:
```error
11-16 22:03:39.508 15824-15824/laoitdev.com.laoautism E/InputEventSender: Exception dispatching finished signal.
11-16 22:03:39.508 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI: java.lang.ClassCastException: android.support.v7.internal.view.ContextThemeWrapper cannot be cast to android.app.Activity
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at com.quinny898.library.persistentsearch.SearchBox.dispatchKeyEvent(SearchBox.java:948)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1470)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1470)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1470)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1470)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1470)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1470)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:2262)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at com.android.internal.policy.impl.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1612)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at android.app.Activity.dispatchKeyEvent(Activity.java:2524)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at android.support.v7.internal.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:49)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:265)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at android.support.v7.internal.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:49)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2181)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4659)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4626)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4191)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4245)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4214)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4325)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4222)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4382)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4191)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4245)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4214)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4222)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4191)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4245)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4214)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4358)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4518)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2215)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1863)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1854)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2192)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at android.os.MessageQueue.nativePollOnce(Native Method)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at android.os.MessageQueue.next(MessageQueue.java:138)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at android.os.Looper.loop(Looper.java:131)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at android.app.ActivityThread.main(ActivityThread.java:5602)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at java.lang.reflect.Method.invokeNative(Native Method)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at java.lang.reflect.Method.invoke(Method.java:515)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
11-16 22:03:39.528 15824-15824/laoitdev.com.laoautism E/MessageQueue-JNI:     at dalvik.system.NativeStart.main(Native Method)
```

**Comment by ajans** [comment]
Could you please test this aar with my fix-wip?

https://www.dropbox.com/s/4y5zr8rj47bjrog/library-release.aar?dl=0

I am preparing a pull request that fixes all currently known backbutton-issues and your feedback would help as I don't have code to really test this.

In essence, I introduced a code snippet method called scanForActivity which is called in the SearchBox-constructor. What it does, is, it first checks getContext() to be an activity, and if so, uses that directly. Otherwise, it handles the ContextWrapper-case, unwraps that wrapper recursively until it finds an activity or no context could be found (which would really be strange, since the SearchBox should always be in a general activity-context).

**Comment by KiengKnot** [comment]
Thank you for you interest with this error.

here again, i have figured out something which is weird.
(1)Today i have roll back the old version of my project with old PersistentSearch library(when there was not include this method)
```
            @Override
            public void onResultClick(SearchResult result) {
                Log.d(TAG, "onResultClick");
                //React to a result being clicked
            }
```
 reopen it and test normally, and it work, but it come out with some bug which was introduced in #82 .
then i tried to implement new PersistentSearch library version(1.1.0-SNAPSHOT), and the result is error (not working)
(2) but when i tried to implement old library to my current project, both old and new project, the result is error.

summary:
I know i make a bit mass on my project, but i confuse when
1. your demo app(new one) is work properties, also the old one.
2. your old library version is work fine with my old project version but not my current project version.
2. your new library version is not work with all my project version.

My project:
1. I use pager in my project with 4 pages.
2. I use PersistentSearch in the Main activity of Pager (implement search View in MainActivity Layout).
3. I query data every time on ```onSearchTermChanged()``` by Loader when finished send the result to first fragment by ```interface```

Thank you.

**Comment by KiengKnot** [comment]
Thank you, it's work now
[https://www.dropbox.com/s/4y5zr8rj47bjrog/library-release.aar?dl=0](https://www.dropbox.com/s/4y5zr8rj47bjrog/library-release.aar?dl=0)

    public boolean dispatchKeyEvent(KeyEvent e) {
        if(e.getKeyCode() == 4 && e.getAction() == 1 && this.getVisibility() == 0 && this.searchOpen) {
            if(this.revealedFromMenuItem) {
                if(this.activity != null) {
                    this.closeSearch();
                    this.hideCircularly(this.activity);
                }
            } else {
                this.toggleSearch();
            }

            return true;
        } else {
            return super.dispatchKeyEvent(e);
        }
    }

**Comment by ajans** [comment]
Thank you for testing! :-)

**Comment by ajans** [comment]
The Pull Request #88 with the fix is open, lets hope Quinny898 merges it soon.

**Comment by CillianMyles** [comment]
I came across the same issue, but thankfully came here before trying to solve the issue myself. 

Thanks @ajans for your work, great job! And thank you @KiengKnot also.
