### ISSUE TITLE
don't work in api 23

### ISSUE THREAD

**Issue by sajadmartiny** [Quinny898/PersistentSearch#90]
hi all ,
i am using this library in my project and don't work in api 23 ,i cant typing anything in search box and don't show hint's .
pls help me,

**Comment by Quinny898** [comment]
It definitely does work in 23, I'm using it in one of my apps aimed mostly at 23 users

**Comment by KiengKnot** [comment]
Report: i confirm that it doesn't work in my project with API 23. the search UI is invisible. but be able to search.

**Comment by anaselhajjaji** [comment]
I confirm it doesn't work on my side as well, is there any solution?

**Comment by anaselhajjaji** [comment]
I just fixed it, I had the Search View inside CoordinatorLayout so I made the Search View and the CoordinatorLayout inside a relative layout and it worked perfectly.

**Comment by KiengKnot** [comment]
i am sorry, that was my mistake. i have done like you. and then it works.
the point is Search UI is hidden by another layout, It would work if you bring Search Widget over another present widget. (move Search Widget to the proper bottom of your XML, lower code of Widget will appear higher on screen)

"This issue can be close"

**Comment by Nxt3** [comment]
@anaselhajjaji Could you share how your layout looks given this workaround?

**Comment by KiengKnot** [comment]
``` XML
<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/main_content"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:clipToPadding="false"
    android:fitsSystemWindows="true"
    android:focusable="false"
    android:focusableInTouchMode="false"
    android:theme="@style/AppTheme"
    tools:context=".MainActivityTab">

    <android.support.design.widget.AppBarLayout
        android:id="@+id/appbar_layout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <android.support.design.widget.CoordinatorLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <android.support.v7.widget.Toolbar
                android:id="@+id/main_toolbar"
                android:layout_width="match_parent"
                android:layout_height="?attr/actionBarSize"
                android:background="?attr/colorPrimaryDark"
                android:popupTheme="@style/ThemeOverlay.AppCompat.Light"
                android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar"
                app:layout_scrollFlags="scroll|enterAlways">

            </android.support.v7.widget.Toolbar>

            <!--Put it below toolbar, then it will show over toolbar-->

            <com.quinny898.library.persistentsearch.SearchBox
                android:id="@+id/searchBox"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_alignParentTop="true"
                android:layout_marginLeft="-6dp"
                android:layout_marginRight="-6dp"
                android:layout_marginTop="-6dp"
                android:gravity="left"
                android:visibility="gone" />

        </android.support.design.widget.CoordinatorLayout>

        <android.support.design.widget.TabLayout
            android:id="@+id/main_tabLayout"
            android:layout_width="match_parent"
            android:layout_height="@dimen/PagerTabStrip_height"
            android:layout_gravity="top"
            android:background="@color/primary"
            android:fillViewport="false"
            android:theme="@style/CustomTabLayout"
            app:tabGravity="fill"
            app:tabMode="fixed" />

    </android.support.design.widget.AppBarLayout>

    <android.support.v4.view.ViewPager

        android:id="@+id/main_viewPager"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_weight="1"
        android:background="@android:color/white"
        app:layout_behavior="@string/appbar_scrolling_view_behavior" />
    
</android.support.design.widget.CoordinatorLayout>
```

**Comment by MOMANI1** [comment]
I used this library in my project  and worked fine until last night, the activity that contain SearchBox crashed when I tested my app on marshmallow emulator, i tested again on API 16 worked fine
whats the problem 
and today its work fine on marshmallow

**Comment by MOMANI1** [comment]
error report
` Process: android.alcode.com.material, PID: 16210
                                                                             java.lang.RuntimeException: Unable to start activity ComponentInfo{android.alcode.com.material/android.alcode.com.material.main.MainActivity}: android.view.InflateException: Binary XML file line #12: Binary XML file line #32: Error inflating class com.quinny898.library.persistentsearch.SearchBox
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                                 at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                              Caused by: android.view.InflateException: Binary XML file line #12: Binary XML file line #32: Error inflating class com.quinny898.library.persistentsearch.SearchBox
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                                 at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276)
                                                                                 at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:136)
                                                                                 at android.alcode.com.material.main.MainActivity.onCreate(MainActivity.java:51)
                                                                                 at android.app.Activity.performCreate(Activity.java:6237)
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                                 at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:148) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                              Caused by: android.view.InflateException: Binary XML file line #32: Error inflating class com.quinny898.library.persistentsearch.SearchBox
                                                                                 at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
                                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
                                                                                 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
                                                                                 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
                                                                                 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                                 at android.view.LayoutInflater.parseInclude(LayoutInflater.java:971)
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:831)
                                                                                 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                                 at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276) 
                                                                                 at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:136) 
                                                                                 at android.alcode.com.material.main.MainActivity.onCreate(MainActivity.java:51) 
                                                                                 at android.app.Activity.performCreate(Activity.java:6237) 
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                                 at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:148) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                              Caused by: java.lang.reflect.InvocationTargetException
                                                                                 at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                                 at android.view.LayoutInflater.createView(LayoutInflater.java:619)
                                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                                 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
                                                                                 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
                                                                                 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                                 at android.view.LayoutInflater.parseInclude(LayoutInflater.java:971) 
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:831) 
                                                                                 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                                 at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276) 
                                                                                 at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:136) 
                                                                                 at android.alcode.com.material.main.MainActivity.onCreate(MainActivity.java:51) 
                                                                                 at android.app.Activity.performCreate(Activity.java:6237) 
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                                 at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:148) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                              Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.balysv.materialmenu.ps.MaterialMenuView.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
                                                                                 at com.quinny898.library.persistentsearch.SearchBox.<init>(SearchBox.java:128)
                                                                                 at com.quinny898.library.persistentsearch.SearchBox.<init>(SearchBox.java:105)
                                                                                 at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                                 at android.view.LayoutInflater.createView(LayoutInflater.java:619) 
                                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                                 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
                                                                                 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
                                                                                 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                                 at android.view.LayoutInflater.parseInclude(LayoutInflater.java:971) 
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:831) 
                                                                                 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                                 at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276) 
                                                                                 at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:136) 
                                                                                 at android.alcode.com.material.main.MainActivity.onCreate(MainActivity.java:51) 
                                                                                 at android.app.Activity.performCreate(Activity.java:6237) 
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                                 at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:148) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) `
