### ISSUE TITLE
ClassCast Exception SearchBox cannot be cast to android.widget.EditText

### ISSUE THREAD

**Issue by vgravariya** [Quinny898/PersistentSearch#98]
Using searchbox in AppCompatActivity.

 FATAL EXCEPTION: main
                                                                         Process: com.kchiekoo.fkm, PID: 9200
                                                                         java.lang.RuntimeException: Unable to start activity ComponentInfo{com.kchiekoo.fkm/com.kchiekoo.fkm.Search}: android.view.InflateException: Binary XML file line #66: Error inflating class com.quinny898.library.persistentsearch.SearchBox
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
                                                                             at android.app.ActivityThread.access$800(ActivityThread.java:144)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:135)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5221)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
                                                                          Caused by: android.view.InflateException: Binary XML file line #66: Error inflating class com.quinny898.library.persistentsearch.SearchBox
                                                                             at android.view.LayoutInflater.createView(LayoutInflater.java:633)
                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                                                                             at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256)
                                                                             at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
                                                                             at com.kchiekoo.fkm.Search.onCreate(Search.java:85)
                                                                             at android.app.Activity.performCreate(Activity.java:5937)
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360) 
                                                                             at android.app.ActivityThread.access$800(ActivityThread.java:144) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:135) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5221) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694) 
                                                                          Caused by: java.lang.reflect.InvocationTargetException
                                                                             at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                             at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                                             at android.view.LayoutInflater.createView(LayoutInflater.java:607)
                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                             at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256) 
                                                                             at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109) 
                                                                             at com.kchiekoo.fkm.Search.onCreate(Search.java:85) 
                                                                             at android.app.Activity.performCreate(Activity.java:5937) 
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105) 
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251) 
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360) 
                                                                             at android.app.ActivityThread.access$800(ActivityThread.java:144) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:135) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5221) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694) 
                                                                          Caused by: java.lang.ClassCastException: com.quinny898.library.persistentsearch.SearchBox cannot be cast to android.widget.EditText
                                                                             at com.quinny898.library.persistentsearch.SearchBox.<init>(SearchBox.java:121)
                                                                             at com.quinny898.library.persistentsearch.SearchBox.<init>(SearchBox.java:105)
                                                                             at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                             at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
                                                                             at android.view.LayoutInflater.createView(LayoutInflater.java:607) 
                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                             at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256) 
                                                                             at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109) 
                                                                             at com.kchiekoo.fkm.Search.onCreate(Search.java:85) 
                                                                             at android.app.Activity.performCreate(Activity.java:5937) 
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105) 
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251) 
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360) 
                                                                             at android.app.ActivityThread.access$800(ActivityThread.java:144) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:135) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5221) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by Quinny898** [comment]
In your layout XML do you have another element with the id of "search"?

**Comment by davidecirillo** [comment]
I've got the same problem:
Caused by: android.view.InflateException: Binary XML file line #48: Error inflating class com.quinny898.library.persistentsearch.SearchBox
and
Caused by: android.view.InflateException: Binary XML file line #34: Binary XML file line #34: Error inflating class TextView
and i don't have any TextView in my xml..
